### ISSUE TITLE
打开扫描界面，图像还是会拉伸

### ISSUE THREAD

**Issue by Dawnton** [0xZhangKe/QRCodeView#3]
你好 升级到1.2版本后在小米4c和联想的某些机型和很多智能POS机上还是会纵向拉伸，华为的不会

**Comment by 0xZhangKe** [comment]
@Dawnton 更新到1.3试试，我这里没有这种机型的，没法调试。

**Comment by Dawnton** [comment]
@0xZhangKe 效果比原来好多了，非常感谢
